apiVersion: v1
kind: Namespace
metadata:
 name: deploy-generator
---
apiVersion: apps/v1
kind: Deployment
metadata:
 namespace: deploy-generator
 name: $deploy-name-tst-app-dep
 labels:
  app: $deploy-name-tst-app
  tier: client
  version: v1
spec:
 selector:
  matchLabels:
   app: $deploy-name-tst-app
   tier: client
   version: v1
 replicas: 1
 template:
  metadata:
   labels:
    app: $deploy-name-tst-app
    tier: client
    version: v1
  spec:
   containers:
   - name: $deploy-name-tst-app
     image: $image-name
     env:   
     resources:
      requests:
       cpu: 25m
       memory: 100Mi
      limits:
       cpu: 100m
       memory: 300Mi
     terminationMessagePath: /tst/termination-log
     terminationMessagePolicy: File
     imagePullPolicy: Always
   restartPolicy: Always
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 25%
   maxSurge: 25%