apiVersion: v1
kind: Namespace
metadata:
  name: deploy-generator
---
apiVersion: v1
kind: Service
metadata:
  name: $deploy-name-svc
  namespace: deploy-generator
  annotations:
    dns_zone: public
  labels:
    app: $deploy-name
    tier: api
    version: v1
spec:
  type: LoadBalancer
  ports:
  - name: port-ext
    port: 80
    targetPort: 80
  selector:
    app: $deploy-name
    tier: api
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: deploy-generator
  name: $deploy-name-dep
  labels:
    app: $deploy-name
    tier: api
    version: v1
spec:  
  selector:
    matchLabels:
      app: $deploy-name
      tier: api
      version: v1
  replicas: 1
  template:
   metadata:
    labels:
      app: $deploy-name
      tier: api
      version: v1
   spec:
     hostAliases:
      - ip: "10.0.14.68"
        hostnames:
        - "trax-apitst.azul.corp"
     containers:       
     -  name: $deploy-name
        image: $image-name
        lifecycle:
            postStart:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/echo 'options single-request-reopen' >> /etc/resolv.conf
        env:
        ports:
        - name: http 
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:  
            path: /health/live
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 25m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 300Mi
        terminationMessagePath: /tst/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
     restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%