apiVersion: v1
kind: Namespace
metadata:
  name: __k8s.namespace__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: __k8s.namespace__
  name: $deploy-name-__environment__
  annotations:
    apigtw: private
  labels:
    app: $deploy-name-__environment__
    tier: api
    version: v1
spec:
  selector:
    matchLabels:
      app: $deploy-name-__environment__
      tier: api
      version: v1
  replicas: 1
  template:
   metadata:
    labels:
      app: $deploy-name-__environment__
      tier: api
      version: v1
   spec:
     hostAliases:
      - ip: "10.0.14.68"
        hostnames:
        - "trax-apitst.azul.corp"
      - ip: "10.0.14.69"
        hostnames:
        - "trax-apihml.azul.corp"
      - ip: "10.0.14.70"
        hostnames:
        - "trax-api.azul.corp"
      - ip: "10.0.6.74"
        hostnames:
        - "ora19odsutb01p.azul.corp"
      - ip: "10.0.11.91"
        hostnames:
        - "ora19dbsh-scan"  
     containers:       
     -  name: $deploy-name-__environment__
        image: $image-name
        lifecycle:
            postStart:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/echo 'options single-request-reopen' >> /etc/resolv.conf
        env:
        ports:
        - name: http 
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: __k8s.app.resources.requests.cpu__
            memory: __k8s.app.resources.requests.memory__
          limits:
            cpu: __k8s.app.resources.limits.cpu__
            memory: __k8s.app.resources.limits.memory__
        terminationMessagePath: /__environment__/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
     restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: __k8s.namespace__
  name: $deploy-name-__environment__-hpa
spec:
  minReplicas: __k8s.app.resources.min.replicas__
  maxReplicas: __k8s.app.resources.max.replicas__
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $deploy-name-__environment__
  metrics:
   - type: Resource
     resource:
        name: cpu
        target:
          averageUtilization: 95
          type: Utilization
   - type: Resource
     resource:
        name: memory
        target:
          averageUtilization: 95
          type: Utilization